/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import entities.CEO;
import entities.Employee;
import exceptions.PersistenceException;
import java.util.List;
import javax.swing.JOptionPane;
import persistence.CEOService;
import persistence.EmployeeService;
import tables.CEOTableModel;
import tables.EmployeeTableModel;

/**
 *
 * @author Marci
 */
public class MainForm extends javax.swing.JFrame {

    private CEOTableModel ceoTableModel;
    private EmployeeTableModel employeeTableModel;
    private List<Employee> employees;
    private List<CEO> ceos;
    private EmployeeService employeeService;
    private CEOService ceoService;

    public MainForm() {
        initComponents();
        employeeService = new EmployeeService();
        ceoService = new CEOService();
        initEmployeeList();
        initCeosList();
        employeeTableModel = new EmployeeTableModel(employees);
        tblEmployee.setModel(employeeTableModel);
        ceoTableModel = new CEOTableModel(ceos);
        tblCEOs.setModel(ceoTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpEmployees = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCEOs = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmployee);

        tpEmployees.addTab("Employees", jScrollPane1);

        tblCEOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCEOs);

        tpEmployees.addTab("CEOs", jScrollPane2);

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btUpdate)
                    .addComponent(btDelete)
                    .addComponent(jRadioButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        EmployeeEventListener l = new EmployeeEventListener();
        EmployeeEditorForm form = new EmployeeEditorForm(this);
        form.addEventListener(l);
        form.setVisible(true);
    }//GEN-LAST:event_btAddActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        if (isRowSelected()) {
            int i = tblEmployee.getSelectedRow();
            EmployeeEventListener l = new EmployeeEventListener();
            EmployeeEditorForm form = new EmployeeEditorForm(this, employees.get(i));
            form.addEventListener(l);
            form.setVisible(true);
        }
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        if (isRowSelected()) {
            try {
                int i = tblEmployee.getSelectedRow();
                employeeService.delete(employees.get(i).getId());
                employees.remove(i);
                employeeTableModel.fireTableDataChanged();
            } catch (PersistenceException ex) {
                JOptionPane.showMessageDialog(this, "Delete error");
            }
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void initEmployeeList() {
        try {
            employees = employeeService.getAllEntities();
        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this, "Cannot load employees");
        }
    }

    private void initCeosList() {
        try {
            ceos = ceoService.getAllEntities();
        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this, "Cannot load employees");
        }
    }

    private boolean isRowSelected() {
        return tblEmployee.getSelectedRow() >= 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCEOs;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTabbedPane tpEmployees;
    // End of variables declaration//GEN-END:variables

    private class EmployeeEventListener implements EntityEventListener<Employee> {

        @Override
        public void entityAdded(Employee t) {
            employees.add(t);
            refreshTable();
        }

        @Override
        public void entityUpdated(Employee t) {
            update(t);
            refreshTable();
        }

        @Override
        public void entityDeleted(Employee t) {
            employees.remove(t);
            refreshTable();
        }

        private void refreshTable() {
            employeeTableModel.fireTableDataChanged();
        }

        private void update(Employee e) {
            int i = 0;
            boolean found = false;
            while (i < employees.size() && !found) {
                if (employees.get(i).
                        getId().
                        equals(e.getId())) {
                    employees.set(i, e);
                    found = true;
                }
                i++;
            }
        }
    }
}
